config/routes.rb
Rails.application.routes.draw do
  resources :galleries, only: [:index, :show]

  root to: 'galleries#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
    @images = @gallery.gallery_images
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/index.html.haml
.row
  - @galleries.each do |gallery|
    .col-md-4
      .thumbnail
        .image.gallery
          = link_to image_tag(gallery.image_url(:medium), alt: gallery.name, title: gallery.description), gallery_path(gallery)
        .caption
          = link_to gallery.name, gallery_path(gallery)

app/views/galleries/show.html.haml
%h1= @gallery.name
.row
  - @images.each do |image|
    .col-md-3
      .thumbnail
        .image.gallery-image
          = link_to image_tag(image.image_url(:medium), alt: image.alt, title: image.description), image.image_url
        .caption
          = image.name
= link_to "<- Back to gallery list", galleries_path, class: 'btn btn-default'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CmsGalleryTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>